# Task 4: Analysis-Ready Table

- Load the revenue, orders, and shipments datasets.
- Reshape the revenue data into its tidy format.
- Recreate the correctly joined orders and shipments table.
- Combine the tidy revenue data and joined order data into one analysis-ready table.
- Make sure the final table has sensible column names, one row per observation, and no leftover index artifacts.

In [1]:
import pandas as pd

revenue = pd.read_csv("../data/company_quarterly_revenue_raw.csv")
orders = pd.read_csv("../data/orders.csv")
shipments = pd.read_csv("../data/shipments.csv")

In [2]:
revenue_tidy = revenue.melt(
    id_vars="company",
    var_name="quarter",
    value_name="revenue"
)

In [3]:
joined_orders = orders.merge(
    shipments,
    on="order_id",
    how="left",
    validate="one_to_many"
)

In [5]:
display(revenue_tidy.head())
display(joined_orders.head())

print(revenue_tidy.columns)
print(joined_orders.columns)

    company  quarter  revenue
0      Acme  2023-Q1     13.5
1    Globex  2023-Q1     10.3
2   Initech  2023-Q1     16.9
3   Soylent  2023-Q1     10.8
4  Umbrella  2023-Q1      8.1

  order_id customer_id  amount   company  quarter tracking
0    O1000        C106      26  Umbrella  2024-Q4  O1000-1
1    O1001        C105      48  Umbrella  2023-Q3  O1001-1
2    O1001        C105      48  Umbrella  2023-Q3  O1001-2
3    O1002        C103     155    Globex  2025-Q2  O1002-1
4    O1003        C100      38      Acme  2023-Q4  O1003-1

Index(['company', 'quarter', 'revenue'], dtype='str')
Index(['order_id', 'customer_id', 'amount', 'company', 'quarter', 'tracking'], dtype='str')

In [9]:
final_table = joined_orders.merge(
    revenue_tidy,
    on=["company", "quarter"],
    how="left"
)

final_table = final_table.reset_index(drop=True)

display(final_table.head())
print("Joined orders rows:", len(joined_orders))
print("Final table rows:", len(final_table))

  order_id customer_id  amount   company  quarter tracking  revenue
0    O1000        C106      26  Umbrella  2024-Q4  O1000-1     10.4
1    O1001        C105      48  Umbrella  2023-Q3  O1001-1      7.7
2    O1001        C105      48  Umbrella  2023-Q3  O1001-2      7.7
3    O1002        C103     155    Globex  2025-Q2  O1002-1     13.8
4    O1003        C100      38      Acme  2023-Q4  O1003-1     16.8

Joined orders rows: 35
Final table rows: 35